services:
  - type: web
    name: career-roadmap
    env: python
    rootDir: .
    branch: master
    buildCommand: pip install -r requirements.txt
    startCommand: python -m streamlit run app.py --server.port $PORT --server.address 0.0.0.0
